services:
  web:
    build: .
    container_name: vtbhackaton-nlp1-web
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - PYTHONPATH=/usr/src/app/src

  db:
    image: postgres:15
    container_name: vtbhackaton-nlp1-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vtbhackaton
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
